development:
  adapter: postgresql
  encoding: unicode
  database: make_companion
  pool: 5
  username: postgres
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: make_companion_test
  pool: 5
  username: postgres
  password: 


production:
  adapter: postgresql
  encoding: unicode
  database: make_companion_production
  pool: 5
  username: postgres
  password: 